### ISSUE TITLE
Additional dependencies

### ISSUE THREAD

**Issue by jkyeung** [arrowtype/recursive-code-config#1]
As it currently stands, this project has at least two dependencies not listed in `requirements.txt`.

The more critical one is PyYAML, which I believe would appear as `pyyaml` in `requirements.txt`.

The other is `fire`, but that could be made optional by adjusting `dlig2calt.py` so that it only imports `fire` if actually needed (by putting the relevant import line inside the `if __name__ == '__main__':` block).

**Comment by arrowtype** [comment]
Hey @jkyeung, it was so awesome of you to take the time to check that out and report my oversight!

I have added pyYAML to the requirements, and converted `dlig2calt.py` to argparse to remove the potential need for `fire`.

I’ve also tested it from a fresh venv this time, so I believe it is now working as it should. 😅

Thanks!
