### ISSUE TITLE
Add TTFautohint into build / instantiation script

### ISSUE THREAD

**Issue by chrisdcao** [arrowtype/recursive-code-config#19]
Do I have any options in the config.yaml or do I have to use ttfautohint manually for hinting? If it's the latter, may you share the settings for hinting this font?
I really miss the Duotone though, I remember it has been in a release 1 year ago or so, but now I can't find it in v84.
Anyway, many thanks in advance!

**Comment by arrowtype** [comment]
Hey @chrisdcao, thanks for asking!

> I really miss the Duotone though, I remember it has been in a release 1 year ago or so, but now I can't find it in v84.

It’s still in [release 1.084](https://github.com/arrowtype/recursive/releases/tag/v1.084), in `ArrowType-Recursive-1-2.084/Recursive_Code/RecMonoDuotone`.

But actually, no, these "code" fonts don’t have hinting, even though they probably should. 

For now, I would recommend using [TTFautohint](https://freetype.org/ttfautohint/index.html) on the command line. Once you [install TTFautohint](https://freetype.org/ttfautohint/#download), the command will be something like:

```bash
ttfautohint "<filepath>/RecMonoDuotone-Regular-1.084.ttf" "<filepath>/RecMonoDuotone-Regular-1.084-hinted.ttf"
```

Depending on the size you are using and the rendering results you get, a useful option to play with is `--increase-x-height`. So, for instance, if you are using the fonts above 14px and some counters are closing up / filling in, and rounding up the x-height might help, try this:

```bash
ttfautohint --increase-x-height=16 font.ttf font-hinted.ttf
```

The default is 14, so if you’re using the font below that, this argument won’t really matter. _OR_ if the x-height is getting stretched and you don’t like that, you could try `--increase-x-height=0`.

I’ll convert this issue to a reminder to myself to add this into the build here, though. It would be sensible and helpful to add in.

**Comment by chrisdcao** [comment]
Cool! Thanks for the reply! 
May I ask what x-height settings you used for the static Desktop code version? I'm very satisfied with that version! Thus if possible, I want to replicate the exact settings you used to create those for my Duotone rendering! Many thanks!

**Comment by arrowtype** [comment]
@chrisdcao 

Looks like the only TTFautohint option used in the build of the main static fonts is `--composites`:

https://github.com/arrowtype/recursive/blob/5b03122edeca493d04b38462c16cb00ef9070f84/mastering/build_static.py#L729-L733

But, [as the TTFA docs say](https://freetype.org/ttfautohint/doc/ttfautohint.html#hint-composites):

> --composites, -c
> By default, the components of a composite glyph get hinted separately. If this flag is set, the composite glyph itself gets hinted (and the hints of the components are ignored). Using this flag increases the bytecode size a lot, however, it might yield better hinting results – usually, it doesn’t.
> 
> If this option is used (and a font actually contains composite glyphs), ttfautohint currently cannot reprocess its own output for technical reasons, see [below](https://freetype.org/ttfautohint/doc/ttfautohint.html#the-.ttfautohint-glyph).

...it may or may not make much of a difference. Still, you probably might as well!

**Comment by arrowtype** [comment]
This has now been added to the script here, and seems to be working for me, in case you’d like to test it out with other configurations. The output fonts are updated in this repo, but not yet in the main recursive release.
