### ISSUE TITLE
Conflicting font names

### ISSUE THREAD

**Issue by jkyeung** [arrowtype/recursive-code-config#3]
The static files generated by this workflow all have the same font name (not just family name). This impedes installation at least on Windows; I don't know about other platforms.

The static files included in `Recursive_Desktop\separate_OTF_TTF_statics\Static_TTF` don't have this problem.

The simplest way to fix this is to add a space and the value of `instance` to the end of `newFullName` in `instantiate-code-fonts.py`.

**Comment by arrowtype** [comment]
Hey @jkyeung, thanks again for taking the time to point out an issue here! Sorry for the headache.

I’ve cleaned up the naming, brought in some metadata fixes that didn’t make it in the first draft, and tested things several things in Windows (on WordPad) to make sure things install & work well.

I think it’s now solid, but please feel free to open this issue back up if not!

**Comment by jkyeung** [comment]
Thanks for the fixes. The naming no longer conflicts, and installation as a font family is now straightforward, so this issue is rightfully closed.

However, I do have other issues, including at least one that's kind of related to naming. I don't know if you'd rather that I reopen this one or open a new one (or maybe neither) but my naming-related issue is this:

Since my use case for this config tool is to create a mildly proportional font with the sans letterforms (MONO axis value less than 0.5), it's a little unfortunate that the naming *must* include `Mono` in it. It's not a big deal, as it's easy enough for me to modify my local copy of the script to allow naming however I like. (There are definitely bigger fish to fry, and if I have time, I'll post more issues.)
