### ISSUE TITLE
Feature ss08 # simplified @ not working

### ISSUE THREAD

**Issue by moconnor1234** [arrowtype/recursive-code-config#5]
When the version was 1.054 ss08 worked, but it does not seem to work since updating to the latest version and rebuilding the fonts.

**Comment by kaushikgopal** [comment]
fwiw: i noticed a similar thing from version `1.52` (where i started noticing this behavior).

**Comment by 0xShamil** [comment]
Seems the issue is still there in version `1.065`

**Comment by bsidhipong** [comment]
Looks like this has been changed to ss12

![image](https://user-images.githubusercontent.com/1375277/96940233-cd7a6d00-1494-11eb-8c70-b70c0a317730.png)

**Comment by 0xShamil** [comment]
`ss08` seems to be working in `1.066`. 

![image](https://user-images.githubusercontent.com/15078409/98648766-b8d71980-235c-11eb-9e10-1d3a28d0a897.png)


@bsidhipong I could not find `ss12` in `ss0x.fea` , even in `1.066` release

**Comment by maxvons** [comment]
`ss12` seems to work for me as well.

**Comment by arrowtype** [comment]
Yes, sorry, ss08 now controls no-serif L & Z, while the simplified @ is now under ss12. (I added in a “simplified italic diagonals” stylistic set, but wanted to keep it next to other lowercase options, and this bumped things around a bit.)

See [OpenType Features in the Readme](https://github.com/arrowtype/recursive/tree/b1bd6704194fd95974bd80035514e63abb5c4aaa#opentype-features).

> I could not find ss12 in ss0x.fea , even in 1.066 release

Not that it really matters to you when you use the fonts, but you can see it here: https://github.com/arrowtype/recursive/blob/b1bd6704194fd95974bd80035514e63abb5c4aaa/src/features/features/ss0x.fea

I’ve just run through the features in 1.066 to check, and it seems like they are all working (at least in FontGoggles, which uses HarfBuzz for text shaping like OT features, etc.)
