### ISSUE TITLE
Script throws an error when all of the config Features are turned off

### ISSUE THREAD

**Issue by mapadev** [arrowtype/recursive-code-config#9]
When running the script with all Features turned off in config.yaml, the script throws:
```
line 226, in <module>
    splitFont()
line 151, in splitFont
    pyftfeatfreeze.main([f"--features=rvrn,{','.join(fontOptions['Features'])}", outputPath, outputPath])
TypeError: can only join an iterable
```

**Comment by jwortmann** [comment]
I think this happens due to an invalid YAML file in that case, rather than a bug in the script. If you want to turn off all features you can specify an empty array in YAML like this:
```yaml
Features: []
```

**Comment by arrowtype** [comment]
My thanks to both of you!

@mapadev, I appreciate the issue. I'll make the script handle this situation more gracefully before closing the issue.

@jwortmann thanks for the suggestion! I haven't tested it yet, but that does seem like a promising workaround until I can get to fixing this in a better way. @mapadev if you want to try it, please let me know if it works!

**Comment by mapadev** [comment]
@arrowtype. The provided solution works for me as I just wanted to try some general settings without embedding any specific features.

Thank you @jwortmann.
